export declare const saveCompanyProfile: (userId: number, companyData: any) => Promise<{
    id: number;
    nome: string;
    descricao: string | null;
    createdAt: Date;
    updatedAt: Date;
    barreiras: string | null;
    isActive: boolean;
    email: string | null;
    telefone: string | null;
    cep: string | null;
    cidade: string | null;
    endereco: string | null;
    estado: string | null;
    password: string | null;
    cnpj: string | null;
    companyData: import("@prisma/client/runtime/library").JsonValue | null;
    nomeFantasia: string | null;
    porte: string | null;
    razaoSocial: string | null;
    setor: string | null;
    site: string | null;
    acessibilidadesOferecidas: string | null;
    bairro: string | null;
    complemento: string | null;
    logradouro: string | null;
    numero: string | null;
    outrasBarreiras: string | null;
    outrosRecursosAcessibilidade: string | null;
    politicasInclusao: string | null;
    possuiSistemaInterno: boolean | null;
    responsavelCargo: string | null;
    responsavelEmail: string | null;
    responsavelNome: string | null;
    responsavelTelefone: string | null;
}>;
export declare const getCompanyProfile: (userId: number) => Promise<{
    id: number;
    nome: string;
    descricao: string | null;
    createdAt: Date;
    updatedAt: Date;
    barreiras: string | null;
    isActive: boolean;
    email: string | null;
    telefone: string | null;
    cep: string | null;
    cidade: string | null;
    endereco: string | null;
    estado: string | null;
    password: string | null;
    cnpj: string | null;
    companyData: import("@prisma/client/runtime/library").JsonValue | null;
    nomeFantasia: string | null;
    porte: string | null;
    razaoSocial: string | null;
    setor: string | null;
    site: string | null;
    acessibilidadesOferecidas: string | null;
    bairro: string | null;
    complemento: string | null;
    logradouro: string | null;
    numero: string | null;
    outrasBarreiras: string | null;
    outrosRecursosAcessibilidade: string | null;
    politicasInclusao: string | null;
    possuiSistemaInterno: boolean | null;
    responsavelCargo: string | null;
    responsavelEmail: string | null;
    responsavelNome: string | null;
    responsavelTelefone: string | null;
} | null>;
//# sourceMappingURL=companyProfile.service.d.ts.map